### ISSUE TITLE
[DOCS] How to use Cloverleaf? Docs?

### ISSUE THREAD

**Issue by ghost** [Refefer/cloverleaf#3]
General Question: how to use this project?

Looking over the code, one can split usage into:
- offline vs online algorithms
- methods for computing node embeddings
- ANN
- SMCI? to tune graph weights,
- random walks

There seems to be an HTTP server at: https://github.com/Refefer/cloverleaf/blob/main/scripts/server.py , I see that there are "node embeddings", "feature embeddings", "feature aggregator". How to generate these? Can you provide some short docs, or examples?

Also wondering about e.g. VPCG: https://github.com/Refefer/cloverleaf/blob/main/src/algos/vpcg.rs#L16-L20 what is "max_terms" here? How does one choose `iterations`?

**Comment by Refefer** [comment]
These are great questions to a woefully ignored document set.  I'm not
working Monday so might be a reasonable thing to tackle.
